"""add_rationale_to_ai_analysis

Revision ID: 7ba671d220bc
Revises: 001
Create Date: 2026-06-12 13:06:34.459194
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7ba671d220bc'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis_scores', sa.Column('rationale', sa.Text(), nullable=True))
    op.alter_column('articles', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('idx_sources_enabled'), table_name='sources', postgresql_where='(enabled = true)')
    op.drop_index(op.f('idx_sources_last_fetched'), table_name='sources')
    op.drop_index(op.f('idx_sources_source_type'), table_name='sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_index(op.f('idx_sources_last_fetched'), 'sources', ['last_fetched_at'], unique=False)
    op.create_index(op.f('idx_sources_enabled'), 'sources', ['enabled'], unique=False, postgresql_where='(enabled = true)')
    op.alter_column('articles', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('ai_analysis_scores', 'rationale')
    # ### end Alembic commands ###
